local harpoon_ui = require("harpoon.ui")
local harpoon_mark = require("harpoon.mark")
vim.keymap.set("n", "<leader>ha", function()
    harpoon_mark.add_file()
end, { desc = "Add file to Harpoon" })
vim.keymap.set("n", "<leader>hm", function()
    harpoon_ui.toggle_quick_menu()
end, { desc = "Toggle Harpoon menu" })
vim.keymap.set("n", "<leader>h1", function()
    harpoon_ui.nav_file(1)
end, { desc = "Go to Harpoon file 1" })
vim.keymap.set("n", "<leader>h2", function()
    harpoon_ui.nav_file(2)
end, { desc = "Go to Harpoon file 2" })
vim.keymap.set("n", "<leader>h3", function()
    harpoon_ui.nav_file(3)
end, { desc = "Go to Harpoon file 3" })
vim.keymap.set("n", "<leader>h4", function()
    harpoon_ui.nav_file(4)
end, { desc = "Go to Harpoon file 4" })

